# Generated by Django 4.2.6 on 2023-11-04 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='photo_main',
            field=models.ImageField(default=2023, upload_to='photos/%Y/%m/%d/'),
            preserve_default=False,
        ),
    ]
