# Generated by Django 4.2.6 on 2023-11-04 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_city_photo_main'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='properties_no',
            field=models.IntegerField(default=2023),
            preserve_default=False,
        ),
    ]
