# Generated by Django 4.2.6 on 2023-11-04 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_city_properties_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='properties_no',
            field=models.IntegerField(default=0),
        ),
    ]
