# Generated by Django 4.2.6 on 2023-11-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0010_listing_parking_alter_listing_garage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.CharField(choices=[('yes', 'Garage_available'), ('no', 'Garage_unavailable')], max_length=4),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(choices=[('yes', 'Parking_available'), ('no', 'Parking_unavailable')], max_length=4),
        ),
    ]
