# Generated by Django 4.2.6 on 2023-11-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_alter_listing_garage_alter_listing_parking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='garage',
            field=models.CharField(choices=[('Garage_available', 'Yes'), ('Garage_unavailable', 'No')], max_length=200),
        ),
        migrations.AlterField(
            model_name='listing',
            name='parking',
            field=models.CharField(choices=[('Parking_available', 'Yes'), ('Parking_unavailable', 'No')], max_length=200),
        ),
    ]
